api_info:
  api_key : 610077b8dbc34769b5f44606522e4920
  api_name : Financial Modeling Prep
  api_link : https://financialmodelingprep.com/developer

country_exchanges:
  US: ["New York Stock Exchange", "NASDAQ"]
  India: ["NSE"]



