windows:
  input: main\data\input\
  output: main\data\output\
  FMP_company_details: main\data\input\FMP_API_data\company_details\
  daily_price: main\data\input\FMP_API_data\daily_price\
  process_daily_price: main\data\output\FMP_API_data\daily_price\
  features: main\data\output\features\
  model_data: main\data\output\model_data\
  cache: main\data\cache\

linux:
  input: main/data/input/
  output: main/data/output/
  company_details: main/data/input/FMP_API_data/company_details/
  daily_price: main/data/input/FMP_API_data/daily_price
  process_daily_price: main/data/output/FMP_API_data/daily_price/
  features: main/data/output/features/
  model_data: main/data/output/model_data/
  cache: main/data/cache/









