windows:
  input: main\data\input\
  output: main\data\output\
  FMP_company_details: main\data\input\FMP_API_data\company_details\
  daily_price: main\data\input\FMP_API_data\daily_price

linux:
  input: main/data/input/
  output: main/data/output/
  company_details: main/data/input/FMP_API_data/company_details/
  daily_price: main/data/input/FMP_API_data/daily_price






