TI_processing_flags:
  country: US
  ticker_list: ["HTH"] # All the tickers present in the folder
  history: all # Change this to number of days as per requirement


variable_names:
  date: 'date'
  open: 'open'
  high: 'high'
  low: 'low'
  close: 'close'
  adj_close: 'adjClose'
  volume: 'volume'
  unadjusted_volume: 'unadjustedVolume'

technical_indicator_inputs:
  column: close
  package: pandas-ta
  available_strategies: None # ['candles', 'cycles', 'momentum', 'performance', 'statistics', 'trend', 'volatility', 'volume']
  indicators_details: [{"kind": "sma", "length": 20},
                       {"kind": "fwma", "length": 20},
                       {"kind": "stoch"},
                       {"kind": "rsi"},
                       {"kind": "macd", "fast": 12, "slow": 26},
                       {"kind": "willr"},
                       {"kind": "adosc"},
                       {"kind": "cci"},
                       {"kind": "mom", "length": 10}]

FC_processing_flags:
  country: US
  ticker_list: all

feature_creation_inputs:
  normalization_method: average
  normalization_tf: 45 #Enter number of days
  create_det_trend_signals: yes
  remove_correlated_variables: no
  historic_datapoint_for_pred: 45
  time_ahead_to_pred: 7
  columns_normalize: ["close", "volume", "vwap"]
















