processing_flags:
  country: US
  ticker_list: all # All the tickers present in the folder
  history: all # Change this to number of days as per requirement

technical_indicator_inputs:
  package: pandas-ta
  available_strategies: None # ['candles', 'cycles', 'momentum', 'performance', 'statistics', 'trend', 'volatility', 'volume']
  indicators_details: [{"kind": "sma", "length": 20},
                       {"kind": "fwma", "length": 20},
                       {"kind": "stoch"},
                       {"kind": "rsi"},
                       {"kind": "macd", "fast": 12, "slow": 26},
                       {"kind": "willr"},
                       {"kind": "adosc"},
                       {"kind": "cci"},
                       {"kind": "mom", "length": 10}]
variable_names:
  date: 'date'
  open: 'open'
  high: 'high'
  low: 'low'
  close: 'close'
  adj_close: 'adjClose'
  volume: 'volume'
  unadjusted_volume: 'unadjustedVolume'





